services:
  - type: web
    name: veenatinnovations-laundry-api
    runtime: node
    plan: free
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: npx prisma db push && npm run prisma:seed && npm run start:prod
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: laundry-db
          property: connectionString
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRATION
        value: 365d
      - key: JWT_REFRESH_EXPIRATION
        value: 365d
      - key: CORS_ORIGIN
        value: "*"

databases:
  - name: laundry-db
    plan: free
    postgresMajorVersion: 15
